name: Automatic create Pull-Request

on:
  push:
    branches: [ dev ]
    
jobs:

  mergeDevIntoMaster:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: master
          base: dev
