name: Automatic create Pull-Request

on:
  push:
    branches: [ dev ]
    
jobs:

  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.8.2
