name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  unittest_log_unterface:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
        working-directory: module_test/log_interface
    steps:
    - uses: actions/checkout@v2
    - name: build unittest
      run: make unittest
    - name: run unittest
      run: make run
